name: Manual Package

on:
  workflow_dispatch:

jobs:

  Build:

    name: Build
    runs-on: windows-2019

    steps:

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Set Git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Clone PyInstaller source
        uses: actions/checkout@v2
        with:
          repository: 'pyinstaller/pyinstaller'
          ref: 'v4.3'
          path: './pyinstaller'

      - name: Build PyInstaller bootloader
        run: |
          cd ./pyinstaller/bootloader
          python ./waf all --target-arch=64bit

      - name: Install PyInstaller
        run: |
          cd ./pyinstaller
          python -m pip install wheel
          python setup.py install

      - name: Clone repo
        uses: actions/checkout@v2
        with:
          path: './F95Checker'

      - name: Build
        run: |
          cd .\F95Checker
          python -m pip install -r requirements.txt
          pyinstaller --clean -y --dist dist\windows --workpath tmp build.spec

      - name: Cleanup + Include .py files
        shell: cmd
        run: |
          cd      .\F95Checker
          del  /f dist\windows\F95Checker\Qt5Bluetooth.dll
          del  /f dist\windows\F95Checker\Qt5DBus.dll
          del  /f dist\windows\F95Checker\Qt5Location.dll
          del  /f dist\windows\F95Checker\Qt5Multimedia.dll
          del  /f dist\windows\F95Checker\Qt5Nfc.dll
          del  /f dist\windows\F95Checker\Qt5QmlWorkerScript.dll
          del  /f dist\windows\F95Checker\Qt5Quick3D.dll
          del  /f dist\windows\F95Checker\Qt5Quick3DAssetImport.dll
          del  /f dist\windows\F95Checker\Qt5Quick3DRender.dll
          del  /f dist\windows\F95Checker\Qt5Quick3DRuntimeRender.dll
          del  /f dist\windows\F95Checker\Qt5Quick3DUtils.dll
          del  /f dist\windows\F95Checker\Qt5QuickControls2.dll
          del  /f dist\windows\F95Checker\Qt5QuickParticles.dll
          del  /f dist\windows\F95Checker\Qt5QuickShapes.dll
          del  /f dist\windows\F95Checker\Qt5QuickTemplates2.dll
          del  /f dist\windows\F95Checker\Qt5QuickTest.dll
          del  /f dist\windows\F95Checker\Qt5RemoteObjects.dll
          del  /f dist\windows\F95Checker\Qt5Sensors.dll
          del  /f dist\windows\F95Checker\Qt5SerialPort.dll
          del  /f dist\windows\F95Checker\Qt5Sql.dll
          del  /f dist\windows\F95Checker\Qt5Svg.dll
          del  /f dist\windows\F95Checker\Qt5Test.dll
          del  /f dist\windows\F95Checker\Qt5WebSockets.dll
          del  /f dist\windows\F95Checker\Qt5XmlPatterns.dll
          mkdir   dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\aiohttp               dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\multidict             dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tcl8                  dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\yarl                  dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\*.pyd                 dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\api-ms-win-*          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\d3dcompiler_47.dll    dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libcrypto-1_1.dll     dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libcrypto-1_1-x64.dll dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libeay32.dll          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libEGL.dll            dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libffi-7.dll          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libGLESv2.dll         dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libssl-1_1.dll        dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\libssl-1_1-x64.dll    dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\MSVCP140_1.dll        dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\MSVCP140.dll          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\opengl32sw.dll        dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\ssleay32.dll          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tcl86t.dll            dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\tk86t.dll             dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\ucrtbase.dll          dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\VCRUNTIME140_1.dll    dist\windows\F95Checker\lib
          move /y dist\windows\F95Checker\VCRUNTIME140.dll      dist\windows\F95Checker\lib
          mkdir   dist\windows\F95Checker\modules
          copy /y F95Checker.py                                 dist\windows\F95Checker
          copy /y F95Checker.sh                                 dist\windows\F95Checker
          copy /y requirements.txt                              dist\windows\F95Checker
          copy /y update.py                                     dist\windows\F95Checker
          copy /y update.exe                                    dist\windows\F95Checker
          copy /y modules                                       dist\windows\F95Checker\modules

      - name: Get short SHA string
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - name: Zip package
        shell: cmd
        run: 7z a -r .\F95Checker-manual-${{ steps.short-sha.outputs.sha }}.zip .\F95Checker\dist\windows\F95Checker\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: F95Checker-manual-${{ steps.short-sha.outputs.sha }}
          path: ./F95Checker-manual-${{ steps.short-sha.outputs.sha }}.zip

      - name: Purge old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
